apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: cve-2019-14287
spec:
  tags: ["CVE"]
  message: "Non Root User Tried to Run sudo Command"
  selector:
    matchLabels:
      pod: testpod
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/sudo
      ownerOnly: true
    - path: /bin/sudo
      ownerOnly: true
    action: Block
