apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-cve-2021-24499-unauthenticated-rce
  namespace: default    #Change with your namespace
spec:
  tags: ["CVE","CVE-2021-24499","unauthenticated-RCE"]
  selector:
    matchLabels:
      app: wordpress
  process:
    severity: 5
    matchDirectories:
    - dir: /var/www/html/wp-content/uploads/workreap-temp/
      recursive: true
    action: Block
  file:
    severity: 5
    matchDirectories:
    - dir: /var/www/html/wp-content/uploads/workreap-temp/
      readOnly: false
      recursive: true
      ownerOnly: false
    action: Block
