apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: t1571-postgresql
spec:
  description: Blocking non-standard ports of postgresql pods
  endpointSelector:
    matchLabels:
      {}
  ingress:
  - toPorts:
    - ports:
      - port: "5432"
        protocol: TCP
