apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-pci-dss-7
spec:
  tags: ["PCI-DSS", "MYSQL"]
  message: "Someone Tried to Access MySQL Files"
  selector:
    matchLabels:
      pod: testpod
  file:
    severity: 5
    matchDirectories:
    - dir: /var/lib/mysql/mysql/
      recursive: true
      readOnly: false
    action: Block
