apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnp-stigs-postgresql-port-external-access
spec:
  description: "This will Block PostgreSQL External Access"
  endpointSelector:
    matchLabels:
      pod: test
  ingress:
    - fromEntities:
        - cluster
    - fromCIDRSet:
        - {}
      toPorts:
        - ports:
            - port: "5432"
