apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-scheduled-task-job-at
spec:
  selector:
    matchLabels:
       {}
  process: 
      matchPaths: 
      - path: /etc/at.allow
      - path: /etc/at.deny
      - path: /usr/bin/at      
      action: Audit
      severity: 2