apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-defense-evasion
spec:
  selector:
    matchLabels:
         {}
  process:
    matchPaths:
    - path: /usr/bin/certutil
    action: Audit
    severity: 5
