apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: network-service-scanning
spec:
  severity: 5
  tags: ["MITRE"]
  message: "listing of services running on remote hosts, including those that may be vulnerable to remote software"
  selector:
    matchLabels:
      {}
  process:
    matchPaths:
    - path: /usr/bin/netstat
    - path: /bin/netstat
    - path: /usr/sbin/ip
    - path: /usr/bin/ip
    - path: /sbin/ip
    - path: /bin/ip
    - path: /usr/sbin/iw
    - path: /sbin/iw
    - path: /usr/sbin/ethtool
    - path: /sbin/ethtool
    - path: /usr/sbin/ifconfig
    - path: /sbin/ifconfig
    - path: /usr/sbin/arp
    - path: /sbin/arp
    - path: /usr/sbin/iwconfig
    - path: /sbin/iwconfig
  action: Audit
