apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: system-file-analysis
spec:
  selector:
    matchLabels:
       {}
  process: 
      matchPaths: 
      - path: /etc/passwd
      - path: /etc/shadow
      action: Audit
      severity: 7 # lowest severity
