apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access-unsecured-credentials-private-keys
spec:
  tags: ["mitre", "system"]
  message: "Private Keys is Audited if someone tries to access it"
  selector:
    matchLabels:
      pod: ubuntu-1          
  file:
    severity: 6
    matchDirectories:
      - dir: /etc/ssl/
        recursive: true
      - dir: /credentials/
        recursive: true
      - dir: /etc/ssh/
    action: Audit
