apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access-unsecured-credentials-private-keys
spec:
  selector:
    matchLabels:
      {}
  file:
    matchDirectories:
      - dir: /etc/ssl/
        recursive: true
      - dir: /credentials/
        recursive: true
      - dir: /etc/ssh/
    action: Audit
    severity: 6
