apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access-password-dumping

spec:
  tags: ["MITRE"]
  message: credential-access-password-dumping
  selector:
      matchLabels:
          {}
  file:
    matchPaths: 
    - path: /etc/passwd
    - path: /etc/shadow
  action:
    Audit
  severity: 4