apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: system-file-analysis
spec:
  severity: 3
  selector:
    matchLabels:
       {}
  process: 
        matchPaths: 
        - path: /etc/passwd
        - path: /etc/shadow
  action:
      Audit