apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
   name: cnp-egress-elastic-tcp-protocol
  namespace: default  #change with your namespace
spec:
  description: "Limits all endpoints with the label app=elastic-operator to only be able to emit packets using TCP on port 443, to any layer 3 destination"
  endpointSelector:
    matchLabels:
      app: elastic-operator   #change with your app
  egress:
  - toPorts:
    - ports:
      - port: "443"
        protocol: TCP
