apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnp-ingress-elastic-tcp-protocol
  namespace: default                    # Change your namespace
spec:
  description: "Allow tcp connections only via 9300 port"
  endpointSelector:
    matchLabels:
      app: elasticsearch                # Change your matchLabels
  ingress:
  - toPorts:
    - ports:
      - port: "9300"
        protocol: TCP
    fromEntities:
    - host
