# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-allow-golang-app-podinfo-podcli-tcp-newtork-access
  namespace: default        #change namespace to match your namespace
spec:
  tags: ["GoLang", "Allow policy", "Baseline policy"]
  message: "Allowed tcp communication on podinfo and podcli"
  selector:
    matchLabels:
      app: podinfo                         #change label to match your label
  network:
    severity: 1
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /home/app/podinfo           #change binary path to match your binary path
      - path: /usr/local/bin/podcli       #change binary path to match your binary path
    action: Allow
