# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-allow-golang-app-access-null-file
  namespace: default        #change namespace to match your namespace
spec:
  tags: ["GoLang", "Allow policy", "Baseline policy","null file"]
  message: "null file accessed by GoLang binary."
  selector:
    matchLabels:
      app: frontend         #change label to match your label
  file:
    severity: 1
    matchPaths:
    - path: /dev/null
      fromSource:
      - path: /src/server   #change binary path to match your binary path
    - path: /etc/ld.so.cache
      fromSource:
      - path: /usr/bin/dash
      - path: /usr/bin/sh
    - path: /lib/x86_64-linux-gnu/libc.so.6
      fromSource:
      - path: /usr/bin/dash
      - path: /usr/bin/sh
    action: Allow
