apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-scheduled-task-job-crontab
spec:
  severity: 5
  selector:
    matchLabels:
       {}
  process: 
        matchPaths: 
        - path: /etc/crontab 
        - path: /usr/sbin/cron
        - path: /etc/cron.d
        - path: /etc/cron.d/cron.allow
        - path: /etc/cron.d/cron.deny
        - path: /etc/cron.daily
        - path: /etc/cron.monthly
        - path: /etc/cron.hourly
        - path: /etc/cron.weekly
  action:
    Audit
  
