apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access-unsecured-credentials-private-keys
  namespace: {}
spec:
  severity: 6
  selector:
    matchLabels:
      container: {}
  file:
    matchDirectories:
      - dir: /etc/ssl/
        recursive: true
      - dir: /credentials/
        recursive: true
      - dir: /etc/ssh/
  action: 
    Audit
