# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-config-kafka-zookeeper-file-access
  namespace: default
spec:
  tags: ["kafka", "system", "allow", "file", "zookeeper"]
  message: "Access allowed to kafka zookeeper files from source processes only"
  severity: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev-kafka
      app.kubernetes.io/managed-by: strimzi-cluster-operator
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/part-of: strimzi-dev-kafka
      strimzi.io/cluster: dev-kafka
      strimzi.io/kind: Kafka
      strimzi.io/name: dev-kafka-zookeeper
  file:
    matchPaths:
    - path: /dev/urandom
      fromSource:
      - path: /usr/bin/ncat
    - path: /etc/group
      fromSource:
      - path: /usr/bin/coreutils
      - path: /usr/bin/env
    - path: /etc/hosts
      fromSource:
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
    - path: /etc/ld.so.cache
      fromSource:
      - path: /usr/bin/bash
      - path: /usr/bin/coreutils
    - path: /etc/nsswitch.conf
      fromSource:
      - path: /usr/bin/bash
    - path: /etc/passwd
      fromSource:
      - path: /usr/bin/bash
    - path: /lib64/libtinfo.so.6
      fromSource:
      - path: /usr/sbin/bash
    - path: /opt/kafka/zookeeper_healthcheck.sh
      fromSource:
      - path: /usr/bin/bash
    - path: /var/lib/zookeeper/data/version-2
      fromSource:
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
    matchDirectories:
    - dir: /etc/
      fromSource:
      - path: /opt/kafka/zookeeper_healthcheck.sh
      - path: /usr/bin/nc
      - path: /usr/bin/ncat
    - dir: /lib64/
      fromSource:
      - path: /opt/kafka/zookeeper_healthcheck.sh
      - path: /usr/bin/bash
      - path: /usr/bin/coreutils
      - path: /usr/bin/nc
      - path: /usr/bin/ncat
      - path: /usr/local/sbin/bash
    - dir: /proc/
      fromSource:
      - path: /opt/kafka/zookeeper_healthcheck.sh
      - path: /usr/bin/coreutils
      - path: /usr/bin/env
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
      - path: /usr/local/bin/bash
      - path: /usr/local/sbin/bash
    - dir: /sys/
      fromSource:
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/javafile:
    matchPaths:
    - path: /dev/urandom
      fromSource:
      - path: /usr/bin/ncat
    - path: /etc/group
      fromSource:
      - path: /usr/bin/coreutils
      - path: /usr/bin/env
    - path: /etc/hosts
      fromSource:
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
    - path: /etc/ld.so.cache
      fromSource:
      - path: /usr/bin/bash
      - path: /usr/bin/coreutils
    - path: /etc/nsswitch.conf
      fromSource:
      - path: /usr/bin/bash
    - path: /etc/passwd
      fromSource:
      - path: /usr/bin/bash
    - path: /lib64/libtinfo.so.6
      fromSource:
      - path: /usr/sbin/bash
    - path: /opt/kafka/zookeeper_healthcheck.sh
      fromSource:
      - path: /usr/bin/bash
    - path: /var/lib/zookeeper/data/version-2
      fromSource:
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
    matchDirectories:
    - dir: /etc/
      fromSource:
      - path: /opt/kafka/zookeeper_healthcheck.sh
      - path: /usr/bin/nc
      - path: /usr/bin/ncat
    - dir: /lib64/
      fromSource:
      - path: /opt/kafka/zookeeper_healthcheck.sh
      - path: /usr/bin/bash
      - path: /usr/bin/coreutils
      - path: /usr/bin/nc
      - path: /usr/bin/ncat
      - path: /usr/local/sbin/bash
    - dir: /proc/
      fromSource:
      - path: /opt/kafka/zookeeper_healthcheck.sh
      - path: /usr/bin/coreutils
      - path: /usr/bin/env
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
      - path: /usr/local/bin/bash
      - path: /usr/local/sbin/bash
    - dir: /sys/
      fromSource:
      - path: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/java
  action: Allow