# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-kafka-entity-operator-process-access
  namespace: default
spec:
  tags: ["kafka", "system", "allow", "process", "entity-operator"]
  message: "Allow kafka entity-operator processes from source processes only"
  severity: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev-kafka
      app.kubernetes.io/managed-by: strimzi-cluster-operator
      app.kubernetes.io/name: entity-operator
      app.kubernetes.io/part-of: strimzi-dev-kafka
      strimzi.io/cluster: dev-kafka
      strimzi.io/kind: Kafka
      strimzi.io/name: dev-kafka-entity-operator
  process:
    matchPaths:
    - path: /opt/strimzi/bin/launch_java.sh
    - path: /usr/bin/java
      fromSource:
      - path: /usr/bin/tini
    - path: /usr/bin/openssl
      fromSource:
      - path: /usr/bin/bash
    - path: /usr/bin/rm
      fromSource:
      - path: /usr/bin/bash
    - path: /usr/bin/tini
  action: Allow