# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-allow-springboot-jar-files
  namespace: default
spec:
  tags: ["springboot", "framework", "jre","jdk"]
  message: "jar files are accessed"
  selector:
    matchLabels:
      app: springboot-product
  file:
    severity: 1
    matchPaths:
    - path: /dev/random
      fromSource:
      - path: /usr/local/openjdk-11/bin/java
    - path: /dev/urandom
      fromSource:
      - path: /usr/local/openjdk-11/bin/java
    - path: /etc/hosts
      fromSource:
      - path: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java
    - path: /spring-boot-bestpractice/spring-boot-bestpractice.jar
      fromSource:
      - path: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java
    - path: /usr/lib/jvm/java-1.8-openjdk/jre/lib/currency.data
      fromSource:
      - path: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java
    - path: /usr/lib/jvm/java-1.8-openjdk/jre/lib/logging.properties
      fromSource:
      - path: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java
    - path: /usr/local/openjdk-11/conf/logging.properties
      fromSource:
      - path: /usr/local/openjdk-11/bin/java
    - path: /usr/local/openjdk-11/conf/security/java.policy
      fromSource:
      - path: /usr/local/openjdk-11/bin/java
  action: Allow

