apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-untrusted-shell-execution
spec:
  selector:
    matchLabels:
      {}
  process:
    matchPaths:
    - path: /bin/bash
    - path: /bin/sh
    - path: /usr/bin/bash
    - path: /usr/bin/env
    - path: /usr/bin/shell
    - path: /bin/ksh
    - path: /etc/init.d      
    - path: /dev/tty 
    - path: /bin/zsh
    - path: /bin/tcsh
    - path: /bin/csh
      fromSource:  # trigger an alert if the source
      - dir: /tmp/
      - dir: /var/
      - dir: /home/
      - dir: /usr/
        recursive: true    
      severity: 2 # Higher severity for processes 
  file:
    - path: /bin/bash
    - path: /bin/sh
    - path: /usr/bin/bash
    - path: /usr/bin/env
    - path: /usr/bin/shell
    - path: /bin/ksh
    - path: /etc/init.d      
    - path: /dev/tty 
    - path: /bin/zsh
    - path: /bin/tcsh
    - path: /bin/csh
      fromSource:
      - path: /bin/bash
      severity: 10  # lowest severity for processes invoked as child process of bash
  action:
    Audit
  tags : ["MITRE","D3fend","Execution","Unix Shell"]