apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-all-egress"
spec:
  description: "Egress default deny. An endpoint can be put into the default deny mode at egress"
  endpointSelector:
    matchLabels:
      role: restricted
  egress:
  - {}
