apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-all-egress"
spec:
  description: "egress default deny"
  endpointSelector:
    matchLabels:
      role: restricted
  egress:
  - {}
