# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-file-allow-proc-dir-from-source
  namespace: default
spec:"
  tags: ["MySQL", "system", "allow", "file", "percona", "percona-xtradb-cluster-operator"]
  message: "Allow access to proc dir only from percona source directory"
  severity: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster-operator
      app.kubernetes.io/part-of: percona-xtradb-cluster-operator
  file:
    matchDirectories:
    - dir: /proc/
      fromSource:
      - path: /usr/local/bin/percona-xtradb-cluster-operator
  action: Allow