# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-process-allow-bash-mysqladmin
  namespace: default
spec:
  tags: ["MySQL", "system", "allow", "process", "bitnami"]
  message: "Allow bash and mysqladmin processes"
  severity: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: mysql
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mysql
      helm.sh/chart: mysql-8.6.1
  process:
    matchPaths:
    - path: /bin/bash
    - path: /opt/bitnami/mysql/bin/mysqladmin
  action: Allow