# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-persistence-blis-rc-scripts
spec:
  tags: ["MITRE", "Persistence"]
  nodeSelector:
    matchLabels:
      {}
  file:
    severity: 5
    matchPaths:
      - path: /etc/rc.local
      - path: /lib/systemd/system/rc-local.service
      - path: /usr/lib/systemd/system/rc-local.service
      - path: /lib/systemd/system/rc-local.service.d/debian.conf
      - path: /usr/lib/systemd/system/rc-local.service.d/debian.conf
    action: Block
