# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-mitre-persistence-bash-profile-audit
spec:
  message: Event-Triggered Execution/bash_profile and bashrc
  tags: ["MITRE"]
  nodeSelector:
    matchLabels:
      {}
  file:
    severity: 2
    matchPaths:
    - path: /etc/profile
    - path: /etc/bash.bashrc
    - path: /etc/.bash_profile
    action: Audit

