apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-mitre-process-injection-proc-mem
spec:
  tags: ["MITRE"]
  message: "Another process may allow access to the process's memory"
  nodeSelector:
    matchLabels:
    	app: testpod
  process:
    severity: 4
    matchPatterns: 
    - pattern: ^/proc/\*/maps$
    - pattern: ^/proc/\*/mem$
    action: Block
