# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-mitre-tactic-defense-evasion
spec:
  message: Modify the kernel to automatically execute programs on system boot
  tags: ["MITRE"]
  nodeSelector:
    matchLabels:
      {}
  process:
    matchPaths:
    - path: /usr/bin/certutil
    action: Audit
    severity: 5
