# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-mitre-create-or-modify-system-process-systemd-service
spec:
  message: Create or modify system process and systemd service 
  tags: ["MITRE"]
  nodeSelector:
    matchLabels:
      {}
  process:
    severity: 3
    matchDirectories:
      - dir: /etc/systemd/system/
        recursive: true
      - dir: /usr/lib/systemd/
        recursive: true
      - dir: /lib/systemd/system/
        recursive: true
      - dir: /home/user/.config/systemd/user/
        recursive: true
    action: Audit
  file:
    severity: 3
    matchDirectories:
      - dir: /etc/systemd/system/
        recursive: true
        readOnly: false
      - dir: /usr/lib/systemd/
        recursive: true
        readOnly: false
      - dir: /lib/systemd/system/
        recursive: true
        readOnly: false
      - dir: /home/user/.config/systemd/user/
        recursive: true
        readOnly: false
    action: Audit
