apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-credential-access-password-dumping
spec:
  tags: ["MITRE", "T1003"]
  message: "Credential access password dumping"
  selector:
      matchLabels:
        container: ubuntu # Change your own labels
  file:
    severity: 4
    matchPaths: 
    - path: /etc/passwd
    - path: /etc/shadow
    action: Audit
