apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:    
  name: ksp-block-mysql-dump-in-pods  
spec:    
  selector:      
    matchLabels:        
      {}    
  process:      
    matchPaths:      
    - path: /usr/bin/mysqldump    
    action: BlockWithAudit    
    severity: 6
