apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-tactic-persistence-createaccount-localaccount
spec:
  selector:
    matchLabels: 
      {}
  process:
    matchPaths:
      - path: /usr/sbin/adduser
      - path: /usr/sbin/useradd
    severity: 4
    action: Audit
  file:
    matchPaths:
      - path: /etc/passwd
      - path: /etc/shadow
    action: Audit
    severity: 4
