apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-T1053-tactic-persistence-create-account-local-account
spec:
  tags: ["MITRE", "T1053"]
  message: "System owner discovery command is blocked"
  selector:
    matchLabels:
      app: ubuntu       #change your labels here
  process:
    severity: 2
    matchPaths:
      - path: /usr/sbin/adduser
      - path: /usr/sbin/useradd
    action: Audit
  file:
    severity: 4
    matchPaths:
      - path: /etc/passwd
      - path: /etc/shadow
    action: Audit
