apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-t1548-001-setuid-setgid
spec:
  message: Blocked the setuid or setgid flag
  tags : ["MITRE","Privilege Escalation","S-Bit"]
  selector:
    matchLabels:
        container: ubuntu  # use your own label here
  process:
    matchPaths: 
    - path: /usr/sbin/groupdel
    - path: /usr/sbin/userdel
    - path: /usr/sbin/chgpasswd
    - path: /usr/sbin/groupmod0o
    - path: /usr/sbin/groupadd
    - path: /usr/sbin/newusers
    - path: /usr/sbin/chpasswd
    - path: /usr/sbin/usermod    
    severity: 2 # Higher severity for processes 
    action: Block
