apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ksp-mitre-T1543-002
spec:
  tags: ["HOST", "MITRE", "PERSISTENCE"]
  message: "someone tried to access system process files"
  nodeSelector:
    matchLabels:
      pod: testpod
  file:
    severity: 5
    matchDirectories:
      - dir: /etc/systemd/system/
        recursive: true
        readOnly: false
      - dir: /usr/lib/systemd/
        recursive: true
        readOnly: false
      - dir: /lib/systemd/system/
        recursive: true
        readOnly: false
    action: Block
