# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-pgsql-audit-non-pgsql
spec:
  tags: ["postgres","system","mitre","T1588"]
  message: "Warning! someone has transferred data from the Postgres data directory"
  selector:
    matchLabels:
       pod: ubuntu      #change the labels
  process:
    severity: 6         #high severity
    matchPaths:
    - path: /bin/mv
    - path: /bin/cp
    - path: /bin/rm
    - path: /bin/rmdir
    - path: /bin/ls
    action: Audit
    matchDirectories:
    - dir: /var/lib/postgresql/data/
       fromSource:
        - path: /usr/lib/postgresql/14/bin/postgres   # trigger an alert if the source
