# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-tactic-credential-access-unsecured-credentials-private-keys
spec:
  tags: ["mitre", "system"]
  message: "Private Keys is Audited if someone tries to access it"
  selector:
    matchLabels:
      pod: ubuntu-1          
  file:
    severity: 6
    matchDirectories:
      - dir: /etc/ssl/
        recursive: true
      - dir: /credentials/
        recursive: true
      - dir: /etc/ssh/
    action: Audit
