apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-tactic-presistence-kernel-modules
spec:
  tags: ["MITRE"]
  message: "Modify the kernel to automatically execute programs on system boot"
  selector:
      matchLabels:
          app: testpod 
  process:
    severity: 6
    matchPaths: 
    - path: /usr/sbin/insmod
    - path: /usr/sbin/modprobe   
    - path: /usr/sbin/rmmod   
  	action: Audit
