apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-tactic-persistence-boot-or-logon-autostart-execution-kernel-modules-and-extensions
spec:
  selector:
    matchLabels:
      {}
  process:
    matchPaths:
      - path: /usr/sbin/modprobe 
      - path: /usr/sbin/insmod 
      - path: /usr/sbin/modinfo
      - path: /usr/sbin/lsmod
    action: Audit
    severity: 4
