apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-cve-2020-1707-postgres-password-dumping
spec:
  message: Blocked postgresql password-dumping
  tags : ["postgresql","credential-access","password-dumping ","CVE-2020-1707"]
  selector:
      matchLabels:
        app: postgresql # here use your own labels
  process:
    matchPaths:
    - path: /etc/passwd
    - path: /etc/passwd-
    - path: /etc/shadow
    - path: /etc/shadow-
    severity: 2 # Higher severity 
  file:
    matchPaths: 
    - path: /etc/passwd
    - path: /etc/passwd-
    - path: /etc/shadow
    - path: /etc/shadow-
      fromSource:  # trigger an alert if the source
       - path: /etc
  action:
    Block
  severity: 7 # lowest severity
