apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: mitre-t1053-003-scheduled-task-job-crontab
spec:
  message: "Adversaries is abused the cron utility to perform task scheduling for initial or recurring execution of malicious code"
  tags: ["MITRE","Execution","crontab"]
  nodeSelector:
    matchLabels:
       pod: ubuntu #change the labels 
  process: 
        matchPaths: 
        - path: /etc/crontab 
        - path: /usr/sbin/cron
        - path: /etc/cron.d
        - path: /etc/cron.d/cron.allow
        - path: /etc/cron.d/cron.deny
        - path: /etc/cron.daily
        - path: /etc/cron.monthly
        - path: /etc/cron.hourly
        - path: /etc/cron.weekly
        severity: 2 # Higher severity 
        action: Audit
  file:
          matchPaths: 
             - path: /etc/crontab 
             - path: /usr/sbin/cron
             - path: /etc/cron.d
             - path: /etc/cron.d/cron.allow
             - path: /etc/cron.d/cron.deny
             - path: /etc/cron.daily
             - path: /etc/cron.monthly
             - path: /etc/cron.hourly
             - path: /etc/cron.weekly
               fromSource:  # trigger an alert if the source
               - path: /etc
               - path: /usr/sbin
          action: Audit
          severity: 7 # lowest severity
