apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ksp-mitre-T1548.001-setuid-setgid
spec:
  message: Blocked the setuid or setgid flag files
  tags : ["MITRE","Privilege Escalation","S-Bit"]
  nodeSelector:
    matchLabels:
        kubernetes.io/hostname: ubuntu  # use your own label here
  process:
    matchPaths: 
    - path: /usr/sbin/groupdel
    - path: /usr/sbin/userdel
    - path: /usr/sbin/chgpasswd
    - path: /usr/sbin/groupmod0o
    - path: /usr/sbin/groupadd
    - path: /usr/sbin/newusers
    - path: /usr/sbin/chpasswd
    - path: /usr/sbin/usermod
      fromSource:  # trigger an alert if the source
      - dir: /tmp/
      - dir: /var/
      - dir: /home/
      - dir: /usr/
        recursive: true    
    severity: 2 # Higher severity for processes 
    action: Block
  
