apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-tactic-execution-remote-code-exec-in-container
spec:
  tags: ["MITRE"]
  message: "Netcat runs inside a container that allows remote code execution"
  selector:
      matchLabels:
          app: testpod
  process:
    severity: 6
    matchPaths: 
    - path: /usr/bin/nc
    - path: /usr/bin/ncat
    action: Audit
