# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-1-proc-path-block
spec:
  selector:
    matchLabels:
      {}
  file:
    matchPaths:
      - path: /etc/selinux/*
      - path: /etc/sysconfig/selinux
      - path: /etc/apparmor.d
    action: Audit
    severity: 6
