apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-restrict-access-mysql-server-config
spec:
  tags: ["mysql","mitre","system"]
  message: "This will restrict to access the mysql server config file"
  selector:
    matchLabels:
      pod: ubuntu      #change the labels
  file:
    severity: 5      # medium severity
    matchPaths:
    - path: /etc/mysql/my.cnf
      ownerOnly: true
    action: Block