apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-non-application-layer-protocol
spec:
  selector:
    matchLabels:
      {}
  process:
    severity: 5
    matchPaths:
    - path: /bin/ping 
    action: Audit
