# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-t1222-002
  namespace: default # Change your namespace
spec:
  message: "Blocking chmod and chown"
  tags : ["MITRE","T1222.002"]
  selector:
    matchLabels:
        app: ubuntu  # use your own label here
  process:
    matchPaths:
    - path: /usr/bin/chmod
    - path: /bin/chmod
    - path: /bin//chmod
    - path: /sbin/chmod
    - path: /usr/bin/chown
    - path: /bin/chown
    - path: /bin//chown
    - path: /sbin/chown
    matchPatterns:
    - pattern: /**/chmod
    - pattern: /**/chown
    severity: 2 # Higher severity for processes 
    action: Block
