apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: restrict-access-mysql-config
spec:
  message: "block access to dir /etc/mysql/"
  selector:
    matchLabels: {}
  file:
    severity: 5
    matchDirectories:
    - dir: /etc/mysql/  # <--- mysql directory
      recursive: true
    action: Block
  process:
    severity: 5
    matchPaths:
      - path: /bin/cd
    action: Block

