# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-config-prometheus-tcp-udp
  namespace: default
spec:
  tags: ["prometheus", "system", "allow", "protocol", "monitoring"]
  message: "prometheus process is allowed to use tcp/udp protocols"
  severity: 1
  selector:
    matchLabels:
      app: prometheus
      chart: prometheus-14.3.0
      component: server
      heritage: Helm
      release: prometheus-pinot
  network:
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /bin/prometheus
    - protocol: udp
      fromSource:
      - path: /bin/prometheus
  action: Allow