apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-ac-2-12-account-management
spec:
  tags: ["NIST", "AC-2"]
  message: "To monitor creation or deletion of user accounts"
  nodeSelector:
    matchLabels:
     {}
  process:
    severity: 5
    matchPaths:
    - path: /usr/sbin/useradd
    - path: /sbin/useradd
    - path: /usr/bin/passwd
    - path: /bin/passwd
    - path: /usr/sbin/usermod
    - path: /sbin/usermod
    - path: /usr/sbin/userdel
    - path: /sbin/userdel
    - path: /usr/bin/chage
    - path: /bin/chage
    action: Block
  file:
    severity: 4
    matchPaths:
    - path: /etc/sudoers
      readOnly: true
    action: Audit
