# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-mongodb-5.1
  namespace: default # Change your namespace
spec:
  tags: ["CIS","MONGODB"]
  message: "Alert! Log Files are Accessed"
  selector:
    matchLabels:
      app: mongo # Change image labels
  file:
    severity: 3
    matchPaths:
    - path: /var/log/mongodb/mongod.log  #path of mongodb version changes
      readOnly: false 
    action: Audit
