# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-apache-tomcat-logs-4.4
  namespace: default  # Change your namespace
spec:
  tags: ["Apache-Tomcat", "CIS", "logs", "tomcat-logs"]
  message: "Alert! Restrict access to Tomcat logs directory"
  selector:
    matchLabels:
      app: apache-tomcat # Change your matchLabels
  file:
    severity: 4
    matchDirectories:
    - dir: /usr/local/tomcat/logs/
    - dir: /var/log/tomcat/
    action: Audit 