# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-mysql-3-10
  namespace: default
spec:
  tags: ["MySQL", "CIS", "rule-3.10", "v8", "v7", "Control-3.3", "Control-14.6"]
  message: "Notification! /etc/mysql/my.cnf has been accessed! keyrings may have been modified."
  selector:
    matchLabels:
      app: mysql 
  file:
    severity: 1
    matchPaths:
    - path: /etc/mysql/my.cnf
    action: Audit
