# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-apache-tomcat-4.6
  namespace: default  # Change your namespace
spec:
  tags: ["Apache-Tomcat", "CIS", "binary-files", "permissions"]
  message: "Someone Accessed to Tomcat binaries directory. Check logs"
  selector:
    matchLabels:
      app: apache-tomcat # Change your matchLabels
  file:
    severity: 2
    matchDirectories:
    - dir: /usr/local/tomcat/bin/
      recurive: true
    action: Audit 