# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-apache-tomcat-2.1
  namespace: default  # Change your namespace
spec:
  tags: ["Apache-Tomcat", "CIS", "Information", "Exposure"]
  message: "Alert! configuration files is accessed "
  selector:
    matchLabels:
      app: apache-tomcat # Change your matchLabels
  file:
    severity: 5
    matchPaths:
    - path: /usr/local/tomcat/conf/server.xml
    action: Audit