# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: vm-hsp-audit-cis-redhat-openshift-1.1.5
spec:
  tags: ["CIS", "1.1.5", "redhat", "openshift", "Scheduler-pod", "kube-scheduler"]
  message: "Access to kubescheduler yaml file is detected."
  file:
    severity: 5
    matchPaths:
      - path: /etc/kubernetes/static-pod-resources/kube-scheduler-pod.yaml
    action: Audit