# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: vm-hsp-audit-cis-docker-1.1.18
spec:
  tags: ["CIS", "rule-1.1.18", "Docker"]
  message: "Access to runc is detected."
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/runc
    action: Audit
