# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: vm-hsp-audit-cis-redhat-openshift-1.1.1
spec:
  tags: ["CIS", "1.1.1", "redhat", "openshift", configuration-file"]
  message: "Access to kubeapiserver yaml file is detected."
  file:
    severity: 4
    matchPaths:
      - path: /etc/kubernetes/manifests/kubeapiserver-pod.yaml
    action: Audit