# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: vm-hsp-audit-cis-ubuntu-6.1.3
spec:
  tags: ["CIS", "rule-6.1.3", "ubuntu"]
  message: "Unauthorised access or modification to etc/shadow detected"
  file:
    severity: 3
    matchPaths:
    - path: /etc/shadow
    ownerOnly: true
    action: Audit
