# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: vm-hsp-audit-cis-docker-3.8
spec:
  tags: ["CIS", "rule-3.8", "Docker"]
  message: "Access to certificate file is detected. Possible violation of CIS rule-3.8"
  file:
    severity: 5
    matchDirectories:
    - dir: /etc/docker/certs.d/
      recursive: true
      readOnly: true
    action: Audit
