# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-config-elastic-operator-protocol-access
  namespace: default
spec:
  tags: ["elasticsearch", "system", "allow", "protocol", "elastic-operator"]
  message: "Allow access to protocols only from elastic-operator process"
  severity: 1
  selector:
    matchLabels:
      control-plane: elastic-operator
  network:
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /elastic-operator
    - protocol: udp
      fromSource:
      - path: /elastic-operator
  action: Allow