# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-elasticsearch-indices
  namespace: default 
spec:
  tags: ["Elasticsearch", "system", "audit", "file"]
  message: "Audit indices directory"
  severity: 1
  selector:
    matchLabels:
      app: elasticsearch
  file:
    matchDirectories:
    - dir: /usr/share/elasticsearch/data/nodes/0/indices/
  action: Audit
