apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-au-10-non-repudiation-2
spec:
  tags: ["NIST", "AU-10", "bash", "system", "ksp"]
  message: "Accessed bash shell configuration files"
  selector:
    matchLabels:
      app: test 
  file:
    severity: 6
    matchPaths:
    - path: /etc/profile
    - path: /root/.bashrc
    - path: /root/.bash_login
    - path: /root/.bash_logout
    action: Audit
