apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-au-10-non-repudiation-1
spec:
  tags: ["NIST", "AU-10", "binary", "system", "logs", "File-Permissions", "ksp"]
  message: "Blocked deletion of system binaries/logs/configuration files or/and accessed the File Permissions commands"
  selector:
    matchLabels:
      app: test                     #Replace app: test with your own labels.
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/chsh
    - path: /bin/chmod
    - path: /bin/chown
    - path: /bin/chgrp
    action: Audit
  file:
    severity: 10
    matchDirectories:
    - dir: /bin/
      fromSource:
      - path: /bin/rm
    - dir: /root/
      fromSource:
      - path: /bin/rm
    - dir: /home/
      fromSource:
      - path: /bin/rm
    - dir: /etc/
      fromSource:
      - path: /bin/rm
    action: Block
