apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: remote-access-and-control
  namespace: default
spec:
  tags: ["NIST","system","ksp","AC-17(1)"]
  message: "warning! someone tried to remote access and control"
  selector:
    matchLabels:
      pod: ubuntu    #change the labels
  process:
    severity: 4       
    matchPaths:
    - path: /usr/bin/ssh
    - path: /etc/ssh
    action: Audit