apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ac-2-12-account-management
spec:
  tags: ["NIST", "AC-2"]
  message: "To monitor creation or deletion of user accounts"
  selector:
    matchLabels:
      app: testpod #change app: testpod to match your label 
  process:
    severity: 5
    matchPaths:
    - path: /usr/sbin/useradd
    - path: /sbin/useradd
    - path: /usr/bin/passwd
    - path: /bin/passwd
    - path: /usr/sbin/usermod
    - path: /sbin/usermod
    - path: /usr/sbin/userdel
    - path: /sbin/userdel
    - path: /usr/bin/chage
    - path: /bin/chage
    action: Audit
  file:
    severity: 6
    matchPaths:
    - path: /etc/sudoers
      readOnly: true
    action: Audit
