apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: cred-change-audit
spec:
  tags: ["NIST","AC-10"] 
  message: "AUDITING SHARED AND GROUP ACCOUNT CREDENTIALS CHANGE "
  selector:
    matchLabels:
      pod: test  #change app: test to match your label
  process:
    severity: 5
    matchPaths:
    - path: /usr/sbin/pwconv
    action: Audit
  file:
    severity: 5
    matchPaths:
    - path: /etc/group
    - path: /etc/group-
    - path: /etc/passwd
    - path: /etc/gshadow
    - path: /etc/gshadow-
    action: Audit
