apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-postgresql-private-keys
spec:
  tags: ["POSTGRESQL"]
  message: "Someone Tried to Access Private Keys"
  selector:
    matchLabels:
      pod: testpod
  process:
    severity: 5
    matchPaths:
    - path: /etc/ssl/private/ssl-cert-snakeoil.key
      ownerOnly: true
    - path: /etc/ssl/certs/ssl-cert-snakeoil.pem
      ownerOnly: true
    - path: /var/run/postgresql/13-main.pg_stat_tmp
      ownerOnly: true
    - path: /var/run/postgresql/13-main.pid
      ownerOnly: true
    action: Block
