apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: postgresql-private-keys
spec:
  severity: 5
  selector:
    matchLabels:
      {}
  process:
    matchPaths:
    - path: /etc/ssl/private/ssl-cert-snakeoil.key
      ownerOnly: true
    - path: /etc/ssl/certs/ssl-cert-snakeoil.pem
      ownerOnly: true
    - path: /var/run/postgresql/13-main.pg_stat_tmp
      ownerOnly: true
    - path: /var/run/postgresql/13-main.pid
      ownerOnly: true
  action:
    Block
