apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-psql-block
spec:
  selector:
    matchLabels:
      {}
  process:
    matchPaths:
    - path: /usr/bin/psql
      ownerOnly: true
    - path: /bin/psql
      ownerOnly: true
    - path: /usr/share/postgresql-common/pg_wrapper
      ownerOnly: true
    severity: 5
    action: Block
