apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: postgresql-config-directory
spec:
  tags: ["PostgreSQL"]
  selector:
    matchLabels:
      {}
  file:
    matchDirectories:
      - dir: /etc/postgresql/
        recursive: true
        readOnly: false
      - dir: /etc/postgresql-common/
        recursive: true
        readOnly: false
    action: Audit
    severity: 5
