apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: sep-ubuntu-3-file-allow
spec:
  severity: 5
  selector:
    matchLabels:
      {}
  process:
    matchPaths:
    - path: /usr/bin/psql
      ownerOnly: true
    - path: /bin/psql
      ownerOnly: true
    - path: /usr/share/postgresql-common/pg_wrapper
      ownerOnly: true
  action: Block
