# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stig-v-230239-deny-krb5-workstation-binary
  namespace: default # Change your namespace
spec:
  tags: ["STIGS", "RHEL8","REDHAT","krb5-workstation"]
  message: "Alert! FTP binary access detected. Violation of STIG v230239"
  selector:
    matchLabels:
      app: rhel8 # <--- add your own match labels
  process:
    severity: 5
    matchPatterns:
      - pattern: /**/*krb5-workstation*
    action: Block
