# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stig-v-230492-deny-rsh-server-binary
  namespace: default # Change your namespace
spec:
  tags: ["STIGS", "RHEL8","REDHAT","rsh-server"]
  message: "Alert! FTP binary access detected. Violation of STIG v230492"
  selector:
    matchLabels:
      app: rhel8 # <--- add your own match labels
  process:
    severity: 5
    matchPatterns:
      - pattern: /**/*rsh-server*
    action: Block
