# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stig-v-230487-deny-telnet-server-binary
  namespace: default # Change your namespace
spec:
  tags: ["STIGS", "RHEL8","REDHAT","telnet-server"]
  message: "Alert! FTP binary access detected. Violation of STIG v230487"
  selector:
    matchLabels:
      app: rhel8 # <--- add your own match labels
  process:
    severity: 5
    matchPatterns:
      - pattern: /**/*telnet-server*
    action: Block
