# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stigs-postgresql-console
spec:
  tags: ["STIGS", "POSTGRESQL"]
  message: "Someone Tried to Access PostgreSQL Database"
  selector:
    matchLabels:
      pod: testpod
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/psql
      ownerOnly: true
    - path: /bin/psql
      ownerOnly: true
    - path: /usr/share/postgresql-common/pg_wrapper
      ownerOnly: true
    action: Block
