apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stig-sv-233531r617333-postgres-block-deletion
spec:
  message: "Caution! Someone tried deleting a postgres data file(s)"
  tags: ["postgres", "STIGS"]
  selector:
    matchLabels:
      app: postgres
  file:
    severity: 2
    matchDirectories:
      - dir: /var/lib/postgresql/data/
        recursive: true
        readOnly: false
        fromSource:
        - path: /bin/rm
        - path: /bin/rmdir
        - path: /bin/mv
    action: Block
