# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stig-restrict-access-to-binaries-mongodb-v-81883
  namespace: default # Change your namespace
spec:
  tags: ["mongodb", "config-files"]
  message: "Alert! mongodb binaries have been accessed"
  selector:
    matchLabels:
      app: mongodb # Change your labels
  process:
    severity: 5 
    matchDirectories:
    - dir: /usr/bin/
      recursive: true              
      ownerOnly: true
    action: Audit
