# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stigs-postgresql-config
spec:
  tags: ["STIGS", "POSTGRESQL"]
  message: "Someone Tried to Access PostgreSQL Config Files"
  selector:
    matchLabels:
      pod: testpod
  file:
    severity: 5
    matchDirectories:
      - dir: /etc/postgresql/
        recursive: true
        readOnly: false
      - dir: /etc/postgresql-common/
        recursive: true
        readOnly: false
    action: Audit
