apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mysql-v-235149-audit-mysql-logs
  namespace: default    #change default to your namespace
spec:
  tags: ["MySQL", "STIG", "V-235149"]
  message: "MySQL was accessed by network or a process"
  selector:
    matchLabels:
      app: mysql        #change app: mysql to your label
  network:
    matchProtocols:
    - protocol: TCP
    severity: 6
    action: Audit
  process:
    matchPatterns:      
    - pattern: /**/mysql* 
    severity: 6
    action: Audit
