apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-stigs-restrict-access-mysql-config
spec:
  tags: ["STIGS", "MYSQL"]
  message: "This will block the access to the mysql config files (/etc/mysql/)"
  selector:
    matchLabels:
      container: mysql # <--- add your own match labels
  file:
    severity: 5
    matchDirectories:
    - dir: /etc/mysql/  # <--- mysql directory
      recursive: true
    action: Block
  process:
    severity: 5
    matchPaths:
      - path: /bin/cd
    action: Block
