apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: protect-stored-cardholder-data
spec:
  severity: 5
  tags: ["pci-dss"]
  selector:
    matchLabels:
      {}
  file:
    matchDirectories:
    - dir: /var/lib/mysql/
      recursive: true
      readOnly: false
    severity: 5  
    action:
      Block
