# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-config-consul-tcp
  namespace: default
spec:
  tags: ["consul", "system", "allow", "protocol"]
  message: "tcp allowed only from consul binary"
  severity: 1
  selector:
    matchLabels:
      chart: consul-3.9.6
      component: consul-consul
      heritage: Helm
      release: consul
  network:
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /bin/consul
  action: Allow