# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-autopol-configure-consul-dir-access
  namespace: default
spec:
  tags: ["consul", "system", "allow", "file"]
  message: "Access to consul dir.allowed only from consul process"
  severity: 1
  selector:
    matchLabels:
      chart: consul-3.9.6
      component: consul-consul
      heritage: Helm
      release: consul
  file:
    matchPaths:
    - path: /dev/null
      fromSource:
      - path: /bin/consul
    matchDirectories:
    - dir: /proc/
      fromSource:
      - path: /bin/consul
  action: Allow