apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: cnp-block-cve-2021-44228-log4j-rmi-access
spec:
  description: "Block CVE-2021-44228 by blocking access to LDAP and RMI ports. Only allow ports which are necessary for the application."
  endpointSelector:
    matchLabels:
      app: java-ms #chnage to your labels
  egressDeny:
  - toEntities:
    - "world"
  - toPorts:
    - ports:
      - port: "1099" #Commonly used LDAP and RMI ports
      - port: "1389"
      - port: "389"
      - port: "636"
  egress:
    - toEntities:
      - "all"
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
           - port: "53" #Allow only the port needed for the application
             protocol: ANY 
          rules:
            dns:
              - matchPattern: "*"
